<?php

namespace Database\Factories;

use App\Models\Invoice;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Invoice>
 */
class InvoiceFactory extends Factory
{
    protected $model = Invoice::class;

    public function definition(): array
    {
        $invoiceDate = now();

        return [
            'user_id' => User::factory(),
            'order_id' => null,
            'invoice_number' => null, // generated by model boot()
            'status' => 'unpaid',
            'subtotal' => 0,
            'discount' => 0,
            'tax' => 0,
            'credit' => 0,
            'total' => 0,
            'amount_paid' => 0,
            'balance' => 0,
            'invoice_date' => $invoiceDate,
            'due_date' => $invoiceDate->copy()->addDays(7),
            'paid_date' => null,
            'cancelled_date' => null,
            'late_fee_added' => false,
            'late_fee_amount' => 0,
            'notes' => null,
            'paid_by' => null,
        ];
    }
}

