<?php

namespace Database\Factories;

use App\Models\Order;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Order>
 */
class OrderFactory extends Factory
{
    protected $model = Order::class;

    public function definition(): array
    {
        return [
            'user_id' => User::factory(),
            'order_number' => null, // generated by model boot()
            'status' => 'pending',
            'total' => 0,
            'discount' => 0,
            'coupon_code' => null,
            'notes' => null,
            'activated_at' => null,
            'suspended_at' => null,
            'terminated_at' => null,
            'activated_by' => null,
        ];
    }
}

